var QUOTES = [
  "Entrei na rua dela com meu carro rebaixado",
  "No meu porta-malas, escutando forró pesado",
  "Eu logo percebi quando ela olhou pra mim",
  "Dei a volta por cima e chamei ela pra sair",
  "Ela aceitou o convite, a gente foi cair na farra",
  "Duas garrafas de vinho, ficou mal intencionada",
  "Foi no banheiro, do nada ela sumiu",
  "Quando fui procurar, com outro cara ela sumiu",
  "Tá rocheda, (tô nem vendo)",
  "Pode crer, você merece um prêmio",
  "Tá rocheda, tô nem vendo",
  "Pode crer, você merece um prêmio",
  "De mulher mais bandida do mundo",
  "O coração que é vagabundo, vagabundo",
  "De mulher mais bandida do mundo",
  "O coração que é vagabundo, vagabundo",
  "Aí, Pedrinho Veloso",
  "O novo bonde da cidade, papai!",
  "Solta o som do paredão, esculhamba aí, fi'",
  "Isso é Barões, gente!",
  "Entrei na rua dela com meu carro rebaixado",
  "No meu porta-malas, escutando forró pesado",
  "Eu logo percebi quando ela olhou pra mim",
  "Dei a volta por cima e chamei ela pra sair",
  "Ela aceitou o convite, a gente foi cair na farra",
  "Duas garrafas de vinho, ficou mal intencionada",
  "Foi no banheiro, do nada ela sumiu",
  "Quando fui procurar, com outro cara ela sumiu",
  "Tá rocheda, (tô nem vendo)",
  "Pode crer, você merece um prêmio",
  "Tá rocheda, tô nem vendo",
  "Pode crer, você merece um prêmio",
  "De mulher mais bandida do mundo",
  "O coração que é vagabundo, vagabundo",
  "De mulher mais bandida do mundo",
  "O coração que é vagabundo, vagabundo",
  "Puxa, papai!Sejam todos bem-vindos!",
  "Levante a mão, levante a mão",
  "Jogue a mão pro céu e diz: Vai, Safadão",
  "Vai, Safadão!",
  "Levante a mão, levante a mão",
  "Jogue a mão pro céu e diz: Vai, Safadão",
  "Vai, Safadão!",
  "Libera a energia, vem viver esse momento",
  "Abra o seu coração porque aqui tem sentimento",
  "Deixa a batida do meu som te dominar",
  "O limite é o céu esqueça tudo e vem pra cá",
  "Alegria, a felicidade no ar",
  "O Safadão vai começar",
  "Alegria, esse é o tempo",
  "Vamos curtir a festa, curtir o som do momento",
  "Cheguei, cheguei!",
  "Levante a mão, levante a mão",
  "Jogue a mão pro céu e diz: Vai, Safadão",
  "Vai, Safadão!",
  "Levante a mão, levante a mão",
  "Jogue a mão pro céu e diz: Vai, Safadão",
  "Vai, Safadão!",
  "Percebo que o tempo já não passa",
  "Você diz que não tem graça amar assim",
  "Foi tudo tão bonito, mas voou pro infinito",
  "Parecido com borboletas de um jardim",
  "Agora você volta",
  "E balança o que eu sentia por outro alguém",
  "Dividido entre dois mundos",
  "Sei que estou amando, mas ainda não sei quem",
  "Não sei dizer o que mudou",
  "Mas nada está igual",
  "Numa noite estranha, a gente se estranha e fica mal",
  "Você tenta provar que tudo em nós morreu",
  "Borboletas sempre voltam e o seu jardim sou eu",
  "Percebo que o tempo já não passa",
  "Você diz que não tem graça amar assim",
  "Foi tudo tão bonito, mas voou pro infinito",
  "Parecido com borboletas de um jardim",
  "Agora você volta",
  "E balança o que eu sentia por outro alguém",
  "Dividido entre dois mundos",
  "Sei que estou amando, mas ainda não sei quem",
  "Não sei dizer o que mudou",
  "Mas nada está igual",
  "Numa noite estranha, a gente se estranha e fica mal",
  "Você tenta provar que tudo em nós morreu",
  "Borboletas sempre voltam e o seu jardim sou eu",
  "Não sei dizer o que mudou",
  "Mas nada está igual",
  "Numa noite estranha, a gente se estranha e fica mal",
  "Você tenta provar que tudo em nós morreu",
  "Borboletas sempre voltam e o seu jardim sou eu",
  "Sempre voltam e o seu jardim sou eu",
  "Quando eu digo que deixei de te amar",
  "É porque eu te amo",
  "Quando eu digo que não quero mais você",
  "É porque eu te quero",
  "Eu tenho medo de te dar meu coração",
  "E confessar que eu estou em tuas mãos",
  "Mas não posso imaginar",
  "O que vai ser de mim",
  "Se eu te perder um dia",
  "Eu me afasto e me defendo de você",
  "Mas depois me entrego",
  "Faço tipo, falo coisas que eu não sou",
  "Mas depois eu nego",
  "Mas a verdade",
  "É que eu sou louco por você",
  "E tenho medo de pensar em te perder",
  "Eu preciso aceitar que não dá mais",
  "Pra separar as nossas vidas",
  "E nessa loucura de dizer que não te quero",
  "Vou negando as aparências",
  "Disfarçando as evidências",
  "Mas pra que viver fingindo",
  "Se eu não posso enganar meu coração?",
  "Eu sei que te amo!",
  "Chega de mentiras",
  "De negar o meu desejo",
  "Eu te quero mais que tudo",
  "Eu preciso do seu beijo",
  "Eu entrego a minha vida",
  "Pra você fazer o que quiser de mim",
  "Só quero ouvir você dizer que sim!",
  "Diz que é verdade, que tem saudade",
  "Que ainda você pensa muito em mim",
  "Diz que é verdade, que tem saudade",
  "Que ainda você quer viver pra mim",
];
